//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneSitesiEntities : DbContext
    {
        public KutuphaneSitesiEntities()
            : base("name=KutuphaneSitesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_CEZA> TBL_CEZA { get; set; }
        public virtual DbSet<TBL_HAREKET> TBL_HAREKET { get; set; }
        public virtual DbSet<TBL_KASA> TBL_KASA { get; set; }
        public virtual DbSet<TBL_KATEGORI> TBL_KATEGORI { get; set; }
        public virtual DbSet<TBL_KITAP> TBL_KITAP { get; set; }
        public virtual DbSet<TBL_PERSONEL> TBL_PERSONEL { get; set; }
        public virtual DbSet<TBL_UYELER> TBL_UYELER { get; set; }
        public virtual DbSet<TBL_YAZARLAR> TBL_YAZARLAR { get; set; }
        public virtual DbSet<TBL_HAKKINDA> TBL_HAKKINDA { get; set; }
        public virtual DbSet<TBL_ILETISIM> TBL_ILETISIM { get; set; }
        public virtual DbSet<TBL_MESAJLAR> TBL_MESAJLAR { get; set; }
        public virtual DbSet<TBL_DUYURU> TBL_DUYURU { get; set; }
    }
}
